package theking530.staticpower.data.tiers.categories;

import java.util.Arrays;
import java.util.List;

import net.minecraftforge.common.ForgeConfigSpec;
import net.minecraftforge.common.ForgeConfigSpec.ConfigValue;
import theking530.api.energy.StaticPowerVoltage;
import theking530.api.energy.StaticVoltageRange;
import theking530.staticpower.StaticPower;

public abstract class TierPowerConfiguration {
	/***********************
	 * Power Configuration
	 ***********************/
	public final ConfigValue<Double> defaultPowerCapacity;
	public final ConfigValue<List<Double>> defaultInputVoltageRange;
	public final ConfigValue<Double> defaultMaximumInputPower;

	public final ConfigValue<StaticPowerVoltage> defaultOutputVoltage;
	public final ConfigValue<Double> defaultMaximumPowerOutput;

	/*********************
	 * Battery Configuration
	 *********************/
	public final ConfigValue<Double> batteryCapacity;
	public final ConfigValue<Double> batteryMaximumPowerOutput;
	public final ConfigValue<Double> batteryOutputVoltage;

	/*********************
	 * Transformer Configuration
	 *********************/
	public final ConfigValue<List<Double>> transformerVoltageRange;

	/*************
	 * Solar Panel
	 *************/
	public final ConfigValue<Double> solarPanelPowerGeneration;
	public final ConfigValue<Double> solarPanelPowerStorage;

	public TierPowerConfiguration(ForgeConfigSpec.Builder builder) {
		defaultPowerCapacity = builder.comment("The amount of power a block of this tier can store (in SW).").translation(StaticPower.MOD_ID + ".config." + "defaultPowerCapacity")
				.define("DefaultPowerCapacity", getDefaultPowerCapacity());

		defaultInputVoltageRange = builder.comment("The input voltage range for powered blocks of this tier (in SV).")
				.translation(StaticPower.MOD_ID + ".config." + "defaultInputVoltageRange").define("DefaultInputVoltageRange", internalGetDefaultInputVoltageRange());
		defaultMaximumInputPower = builder.comment("The maximum power a block of this tier can take (in SW.")
				.translation(StaticPower.MOD_ID + ".config." + "defaultMaximumInputPower").define("DefaultMaximumInputPower", getDefaultMaximumPowerInput());

		defaultOutputVoltage = builder.comment("The voltage a block uses internally when performing work (in SV).")
				.translation(StaticPower.MOD_ID + ".config." + "defaultOutputVoltage").define("DefaultOutputVoltage", getDefaultOutputVoltage());
		defaultMaximumPowerOutput = builder.comment("The maximum power a machine of this tier can use while performing work (in SW).")
				.translation(StaticPower.MOD_ID + ".config." + "defaultMaximumPowerOutput").define("DefaultMaximumPowerOutput", getDefaultMaximumPowerOutput());

		builder.push("Transformer");

		transformerVoltageRange = builder.comment("The voltage range that can be handled by a transformer of this tier (in SV).")
				.translation(StaticPower.MOD_ID + ".config." + "transformerVoltageRange").define("TransformerVoltageRange", internalGetTransformerVoltageRange());

		builder.pop();

		builder.push("Battery");
		batteryCapacity = builder.comment("The amount of power that a non-portable battery of this tier can store (in SW).")
				.translation(StaticPower.MOD_ID + ".config." + "batteryCapacity").define("BatteryCapacity", getBatteryCapacity());
		batteryMaximumPowerOutput = builder.comment("The maximum power that a battery of this tier can output (in SW).")
				.translation(StaticPower.MOD_ID + ".config." + "batteryMaximumPowerOutput").define("BatteryMaximumPowerOutput", getBatteryMaximumPowerOutput());
		batteryOutputVoltage = builder.comment("The maximum power that a battery of this tier can output (in SW).")
				.translation(StaticPower.MOD_ID + ".config." + "batteryOutputVoltage").define("BatteryOutputVoltage", getBatteryOutputVoltage());
		builder.pop();

		builder.push("Solar_Panel");
		solarPanelPowerGeneration = builder.comment("The amount of power generated by a solar panel of this tier per tick (in SW).")
				.translation(StaticPower.MOD_ID + ".config." + "solarPanelPowerGeneration").define("SolarPanelPowerGeneration", this.getSolarPanelPowerGeneration());

		solarPanelPowerStorage = builder.comment("The amount of power a solar panel of this tier can store (in SW).")
				.translation(StaticPower.MOD_ID + ".config." + "solarPanelPowerStorage").define("SolarPanelPowerStorage", this.getSolarPanelPowerGeneration());
		builder.pop();
	}

	protected abstract double getDefaultPowerCapacity();

	protected List<Double> internalGetDefaultInputVoltageRange() {
		return Arrays.asList(0.0, getDefaultOutputVoltage().getVoltage());
	}

	public final StaticVoltageRange getDefaultInputVoltageRange() {
		return new StaticVoltageRange(defaultInputVoltageRange.get().get(0), defaultInputVoltageRange.get().get(1));
	}

	protected abstract double getDefaultMaximumPowerInput();

	protected abstract StaticPowerVoltage getDefaultOutputVoltage();

	protected double getDefaultMaximumPowerOutput() {
		return getDefaultOutputVoltage().getVoltage();
	}

	protected double getBatteryCapacity() {
		return getDefaultPowerCapacity() * 100;
	}

	protected abstract double getBatteryMaximumPowerOutput();

	protected double getBatteryOutputVoltage() {
		return getDefaultOutputVoltage().getVoltage();
	}

	protected List<Double> internalGetTransformerVoltageRange() {
		return Arrays.asList(0.0, getDefaultOutputVoltage().getVoltage() * 2);
	}

	public final StaticVoltageRange getTransformerVoltageRange() {
		return new StaticVoltageRange(transformerVoltageRange.get().get(0), transformerVoltageRange.get().get(1));
	}

	protected abstract double getSolarPanelPowerGeneration();

	protected double getSolarPanelPowerStorage() {
		return getSolarPanelPowerGeneration();
	}
}
